### ISSUE TITLE
Question: The vcc has the end of life?

### ISSUE THREAD

**Issue by master-q** [Microsoft/vcc#3]
I'm a user of https://github.com/verifast/verifast verifier.
Also I believe your vcc is better solution to verify C language implementation.

However, vcc has no changing in 2017 year.
Was vcc dead? Or she are living in Microsoft, internally?

Best regards,
Kiwamu Okabe

**Comment by mmoskal** [comment]
As far as I know, VCC is no longer being used at Microsoft.
